USE ships;

/*
SELECT DISTINCT COUNTRY
FROM SHIPS, CLASSES AS cl
WHERE SHIPS.CLASS = cl.CLASS AND NUMGUNS > ALL (SELECT NUMGUNS FROM CLASSES WHERE cl.NUMGUNS < NUMGUNS);
*/

/*
SELECT CLASS
FROM CLASSES
WHERE CLASS IN (SELECT cl.CLASS FROM CLASSES AS cl, SHIPS, OUTCOMES WHERE SHIPS.CLASS = CLASSES.CLASS AND RESULT = 'sunk' AND SHIPS.NAME = OUTCOMES.SHIP);
*/

/*
SELECT SHIPS.NAME, SHIPS.CLASS
FROM SHIPS, CLASSES
WHERE CLASSES.CLASS = SHIPS.CLASS AND  SHIPS.CLASS IN (SELECT CLASS FROM CLASSES WHERE BORE = 16);
*/

/*
SELECT BATTLE
FROM OUTCOMES
WHERE SHIP IN ( SELECT SHIP FROM OUTCOMES, SHIPS WHERE SHIP = NAME AND CLASS = 'Kongo');
*/

/*
SELECT CLASS, NAME
FROM SHIPS
WHERE CLASS IN ( SELECT CLASS FROM CLASSES AS c WHERE NUMGUNS >= ALL (SELECT NUMGUNS FROM CLASSES WHERE BORE = c.BORE)) ORDER BY CLASS;
*/