USE movies;

/*
SELECT TITLE, NAME
FROM MOVIE JOIN MOVIEEXEC ON CERT# = PRODUCERC#
WHERE MOVIEEXEC.CERT# = (SELECT PRODUCERC# FROM MOVIE WHERE TITLE = 'Star Wars')
*/

/*
SELECT DISTINCT NAME
FROM MOVIEEXEC JOIN MOVIE ON CERT# = PRODUCERC#
JOIN STARSIN ON MOVIETITLE = TITLE
WHERE STARSIN.STARNAME = 'Harrison Ford';
*/

/*
SELECT DISTINCT NAME, STARNAME
FROM STUDIO JOIN MOVIE ON STUDIONAME = NAME
JOIN STARSIN ON MOVIETITLE = TITLE
ORDER BY STUDIO.NAME
*/

/*
SELECT STARNAME, NETWORTH, TITLE
FROM STARSIN JOIN MOVIE ON TITLE = MOVIETITLE
JOIN MOVIEEXEC ON PRODUCERC# =CERT#
WHERE NETWORTH IN (SELECT TOP 1 NETWORTH FROM MOVIEEXEC ORDER BY NETWORTH DESC)
*/

/*
SELECT NAME, MOVIETITLE
FROM MOVIESTAR LEFT JOIN STARSIN ON NAME = STARNAME
WHERE MOVIETITLE IS NULL;
*/