USE ships;

/*
SELECT *
FROM SHIPS RIGHT JOIN CLASSES ON CLASSES.CLASS = SHIPS.CLASS
WHERE SHIPS.NAME IS NOT NULL;
*/

/*
SELECT *
FROM SHIPS FULL JOIN CLASSES ON CLASSES.CLASS = SHIPS.CLASS
WHERE NAME IS NOT NULL OR CLASSES.CLASS IN (SELECT NAME FROM SHIPS);
*/

/*
SELECT COUNTRY, NAME
FROM SHIPS JOIN CLASSES ON SHIPS.CLASS = CLASSES.CLASS
LEFT JOIN OUTCOMES ON NAME = SHIP
WHERE BATTLE IS NULL
ORDER BY COUNTRY, NAME ;
*/

/*
SELECT NAME AS SHIPNAME
FROM SHIPS JOIN CLASSES ON CLASSES.CLASS = SHIPS.CLASS
WHERE NUMGUNS >= 7 AND LAUNCHED = 1916;
*/

/*
SELECT SHIPS.NAME, BATTLES.NAME, BATTLES.DATE
FROM SHIPS JOIN OUTCOMES ON SHIPS.NAME = SHIP
JOIN BATTLES ON BATTLES.NAME = BATTLE
WHERE RESULT = 'sunk'
ORDER BY BATTLES.NAME;
*/

/*
SELECT NAME, DISPLACEMENT, LAUNCHED
FROM SHIPS JOIN CLASSES ON CLASSES.CLASS = SHIPS.CLASS
WHERE NAME = CLASSES.CLASS;
*/

/*
SELECT *
FROM CLASSES LEFT JOIN SHIPS ON CLASSES.CLASS = SHIPS.CLASS
WHERE NAME IS NULL;
*/

/*
SELECT NAME, DISPLACEMENT,NUMGUNS, RESULT
FROM CLASSES JOIN SHIPS ON CLASSES.CLASS = SHIPS.CLASS
JOIN OUTCOMES ON NAME = SHIP
WHERE BATTLE = 'North Atlantic';
*/