USE ships;

/*
SELECT NAME
FROM CLASSES, SHIPS
WHERE CLASSES.CLASS = SHIPS.CLASS AND DISPLACEMENT > 50000;
*/

/*
SELECT SHIPS.NAME, DISPLACEMENT,NUMGUNS
FROM CLASSES, SHIPS, OUTCOMES
WHERE CLASSES.CLASS = SHIPS.CLASS AND SHIPS.NAME = OUTCOMES.SHIP AND OUTCOMES.BATTLE = 'Guadalcanal';
*/

/*
(SELECT COUNTRY
FROM CLASSES
WHERE TYPE = 'bb'
)
INTERSECT
(SELECT COUNTRY
FROM CLASSES
WHERE TYPE =  'bc'
);*/

/*
SELECT SHIPS.NAME
FROM SHIPS, OUTCOMES AS o, BATTLES AS b, OUTCOMES AS o2, BATTLES AS b2
WHERE o.SHIP = dbo.SHIPS.NAME AND b.NAME = o.BATTLE AND o2.SHIP = dbo.SHIPS.NAME 
AND b2.NAME = o2.BATTLE AND o.RESULT = 'damaged' AND b2.DATE > b.DATE
*/