USE ships;

/*
SELECT NAME
FROM CLASSES, SHIPS
WHERE CLASSES.CLASS = SHIPS.CLASS AND DISPLACEMENT > 50000;
*/

/*
SELECT SHIPS.NAME, DISPLACEMENT,NUMGUNS
FROM CLASSES, SHIPS, OUTCOMES
WHERE CLASSES.CLASS = SHIPS.CLASS AND SHIPS.NAME = OUTCOMES.SHIP AND OUTCOMES.BATTLE = 'Guadalcanal';
*/

/*
(SELECT COUNTRY
FROM CLASSES
WHERE TYPE = 'bb'
)
INTERSECT
(SELECT COUNTRY
FROM CLASSES
WHERE TYPE =  'bc'
);*/

/*
(SELECT DISTINCT NAME
FROM SHIPS, OUTCOMES
WHERE SHIPS.NAME = OUTCOMES.SHIP AND RESULT = 'damaged'
)
INTERSECT
(SELECT DISTINCT NAME
FROM SHIPS, OUTCOMES
WHERE SHIPS.NAME = OUTCOMES.SHIP AND RESULT != 'damaged'
);*/
