USE FLIGHTS;

ALTER TABLE FLIGHTS
ADD NUMPASS INT;

UPDATE FLIGHTS
SET NUMPASS = 0
WHERE NUMPASS IS NULL;

ALTER TABLE AGENCIES
ADD NUMBOOK INT

UPDATE AGENCIES
SET NUMBOOK = 0
WHERE NUMBOOK IS NULL;

GO

CREATE TRIGGER T_UPDATE_RESERV
ON BOOKINGS AFTER UPDATE
AS
BEGIN
UPDATE FLIGHTS
SET NUMPASS = (NUMPASS + 1)
WHERE FNUMBER IN (SELECT FNUMBER FROM inserted);
END

GO

CREATE TRIGGER T_DELETE_BOOKINGS
ON BOOKINGS AFTER DELETE
AS
BEGIN
UPDATE AGENCIES
SET NUMBOOK = NUMBOOK - 1
WHERE NAME IN (SELECT NAME FROM deleted)
END;
GO

CREATE TRIGGER T_UPDATE_STATUS_RESERV
ON BOOKINGS AFTER UPDATE
AS
BEGIN
UPDATE FLIGHTS
SET NUMPASS = NUMPASS + 1
WHERE FNUMBER IN (SELECT FNUMBER FROM deleted WHERE STATUS=0) AND
FNUMBER IN (SELECT FNUMBER FROM inserted WHERE STATUS=1)
UPDATE FLIGHTS
SET NUMPASS = NUMPASS - 1
WHERE FNUMBER IN (SELECT FNUMBER FROM deleted WHERE STATUS=1) AND
FNUMBER IN (SELECT FNUMBER FROM inserted WHERE STATUS=0)
END;
GO

