USE ships;
--select * from classes;

--INSERT INTO CLASSES(CLASS,TYPE,COUNTRY, NUMGUNS, BORE, DISPLACEMENT) VALUES('Nelson','bb','Gt.Britain',9,16,34000);
--INSERT INTO SHIPS(NAME,CLASS,LAUNCHED) VALUES('Nelson','Nelson',1927),('Rodney','Nelson',1927)

--DELETE FROM SHIPS WHERE NAME IN (SELECT SHIP FROM OUTCOMES WHERE RESULT = 'sunk');

--UPDATE CLASSES SET BORE *=2.5, DISPLACEMENT /=1.1;