--CREATE VIEW V_BATTLES_MORESHIPS
--AS
--SELECT BATTLE
--FROM OUTCOMES
--GROUP BY BATTLE
--HAVING COUNT(SHIP) > ( SELECT COUNT(SHIP) FROM OUTCOMES WHERE BATTLE = 'Guadalcanal' GROUP BY BATTLE);

--SELECT * FROM V_BATTLES_MORESHIPS;

--CREATE VIEW V_BATTLES_MORECOUNTRIES
--AS
--SELECT BATTLE
--FROM OUTCOMES
--JOIN SHIPS ON SHIPS.NAME = SHIP
--JOIN CLASSES ON CLASSES.CLASS = SHIPS.CLASS
--GROUP BY BATTLE
--HAVING COUNT(COUNTRY) > (SELECT COUNT(COUNTRY) FROM OUTCOMES WHERE BATTLE = 'Guadalcanal' GROUP BY BATTLE);

--SELECT * FROM V_BATTLES_MORECOUNTRIES;

--DROP VIEW V_BATTLES_MORECOUNTRIES;

--DELETE FROM OUTCOMES
--WHERE BATTLE IN
--(SELECT BATTLE 
--FROM OUTCOMES 
--GROUP BY BATTLE
--HAVING COUNT(SHIP) = 1);

--INSERT INTO outcomes VALUES ('Missouri','Surigao Strait', 'sunk'),
--('Missouri','North Cape', 'sunk'),
--('Missouri','North Atlantic', 'ok');
--DELETE FROM OUTCOMES
--WHERE SHIP IN
--(SELECT SHIP
--FROM OUTCOMES
--GROUP BY RESULT, SHIP
--HAVING RESULT = 'sunk' AND COUNT(RESULT) = 2);

--CREATE VIEW V_COUNTRIES_GUADALCANAL
--AS
--SELECT DISTINCT COUNTRY
--FROM OUTCOMES
--JOIN SHIPS ON SHIP = NAME
--JOIN CLASSES ON CLASSES.CLASS = SHIPS.CLASS
--WHERE BATTLE = 'Guadalcanal'

--SELECT DISTINCT BATTLE
--FROM OUTCOMES
--JOIN SHIPS ON SHIP = NAME
--JOIN CLASSES ON CLASSES.CLASS = SHIPS.CLASS
--WHERE COUNTRY IN (SELECT * FROM V_COUNTRIES_GUADALCANAL);

--SELECT COUNTRY, COUNT(DISTINCT BATTLE) AS NUM_BATTLES
--FROM CLASSES
--LEFT JOIN SHIPS ON CLASSES.CLASS = SHIPS.CLASS
--LEFT JOIN OUTCOMES ON NAME = SHIP
--GROUP BY COUNTRY;
