--CREATE DATABASE FLIGHTDB;

USE FLIGHTDB;

CREATE TABLE AIRLINES(
	CODE CHAR(2) CONSTRAINT pk_airlines PRIMARY KEY,
	NAME VARCHAR(50) UNIQUE NOT NULL,
	COUNTRY VARCHAR(50) NOT NULL
);

CREATE TABLE AIRPORTS(
	CODE CHAR(3) CONSTRAINT pk_airports PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL,
	COUNTRY VARCHAR(50) NOT NULL,
	CITY VARCHAR(50) NOT NULL
	CONSTRAINT UQ_AIRPOTRS UNIQUE (NAME,COUNTRY)
);

CREATE TABLE AGENCIES(
	NAME VARCHAR(100) CONSTRAINT pk_agencies PRIMARY KEY,
	CITY VARCHAR(50) NOT NULL,
	COUNTRY VARCHAR(50) NOT NULL,
	NUMBER VARCHAR(50)
);

CREATE TABLE CUSTOMERS(
	ID INT CONSTRAINT pk_cutomers PRIMARY KEY,
	FNAME VARCHAR(50) NOT NULL,
	LNAME VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(50) CHECK(EMAIL LIKE '%@%.%' AND LEN(EMAIL) > 5)
);

CREATE TABLE AIRPLANES(
	CODE CHAR(3) CONSTRAINT pk_airplanes PRIMARY KEY,
	TYPE VARCHAR(50) NOT NULL,
	SEATS INT NOT NULL CHECK (SEATS >= 0),
	YEAR INT NOT NULL
);

CREATE TABLE FLIGHTS(
	FNUMBER CHAR(10) CONSTRAINT pk_flights PRIMARY KEY,
	AIRLINE_OPERATOR CHAR(2) NOT NULL,
	DEP_PORT CHAR(3) NOT NULL,
	ARR_PORT CHAR(3) NOT NULL,
	FLIGHT_TIME TIME NOT NULL,
	FLIGHT_DURATION INT NOT NULL,
	AIRPLANE CHAR(3) NOT NULL,
	CONSTRAINT FK_ARRPORT FOREIGN KEY (ARR_PORT) REFERENCES AIRPORTS(CODE),
	CONSTRAINT FK_DEPPORT FOREIGN KEY (DEP_PORT) REFERENCES AIRPORTS(CODE),
	CONSTRAINT FK_AIRLINE FOREIGN KEY (AIRLINE_OPERATOR) REFERENCES AIRLINES(CODE),
	CONSTRAINT FK_AIRPLANEFLIGHTS FOREIGN KEY (AIRPLANE) REFERENCES AIRPLANES(CODE)
);

CREATE TABLE BOOKINGS(
	CODE VARCHAR(6) CONSTRAINT pk_bookings PRIMARY KEY,
	AGENCY VARCHAR(100) NOT NULL,
	AIRLINE_CODE CHAR(2) NOT NULL,
	FLIGHT_NUMBER CHAR(10) NOT NULL,
	CUSTOMER_ID INT NOT NULL,
	BOOKING_DATE DATE NOT NULL,
	FLIGHT_DATE DATE NOT NULL,
	PRICE DECIMAL(9,2),
	STATUS BIT CHECK (STATUS IN ('1','0')) NOT NULL,
	CONSTRAINT CH_RESERV CHECK (FLIGHT_DATE >= BOOKING_DATE),
	CONSTRAINT FK_AIRLINECODE FOREIGN KEY (AIRLINE_CODE) REFERENCES AIRLINES(CODE),
	CONSTRAINT FK_AGENCY FOREIGN KEY (AGENCY) REFERENCES AGENCIES(NAME),
	CONSTRAINT FK_FNUMBERBOOKING FOREIGN KEY (FLIGHT_NUMBER) REFERENCES FLIGHTS(FNUMBER),
	CONSTRAINT FK_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID)
);