
CREATE VIEW V_FLIGHTS_INF
AS
SELECT AIRLINES.NAME, FNUMBER, COUNT(DISTINCT CUSTOMER_ID) AS CUSTCOUNT
FROM FLIGHTS.dbo.FLIGHTS
JOIN FLIGHTS.dbo.BOOKINGS ON FNUMBER=FLIGHT_NUMBER
JOIN FLIGHTS.dbo.AIRLINES ON AIRLINE_OPERATOR=AIRLINES.CODE
GROUP BY AIRLINES.NAME, FNUMBER;
GO

SELECT *
FROM V_FLIGHTS_INF
GO

CREATE VIEW V_MAXCOUNTCLIENT_BOOKINGS
AS
SELECT LNAME, FNAME, ID
FROM FLIGHTS.dbo.CUSTOMERS
WHERE ID IN 
	(SELECT CUSTOMER_ID
	FROM FLIGHTS.dbo.BOOKINGS AS B1
	GROUP BY AGENCY, CUSTOMER_ID
	HAVING COUNT(DISTINCT CUSTOMER_ID) >= 
		(SELECT TOP 1 COUNT(DISTINCT CUSTOMER_ID)
		FROM FLIGHTS.dbo.BOOKINGS AS B2
		WHERE B1.AGENCY = B2.AGENCY
		GROUP BY AGENCY,CUSTOMER_ID
		ORDER BY COUNT(DISTINCT CUSTOMER_ID) DESC)
	)
GO

SELECT *
FROM V_MAXCOUNTCLIENT_BOOKINGS
GO

CREATE VIEW V_ALLINF_AGENCIES
AS
SELECT *
FROM FLIGHTS.dbo.AGENCIES
WHERE CITY = 'Sofia'
WITH CHECK OPTION
GO

SELECT *
FROM V_ALLINF_AGENCIES
GO

CREATE VIEW V_AGENCIES_NONUMBER
AS
SELECT *
FROM FLIGHTS.dbo.AGENCIES
WHERE PHONE IS NULL
WITH CHECK OPTION
GO

SELECT *
FROM V_AGENCIES_NONUMBER
GO

INSERT INTO V_ALLINF_AGENCIES
VALUES('T1 Tour', 'Bulgaria', 'Sofia','+359');
INSERT INTO V_AGENCIES_NONUMBER
VALUES('T2 Tour', 'Bulgaria', 'Sofia',null);
INSERT INTO  V_ALLINF_AGENCIES
VALUES('T3 Tour', 'Bulgaria', 'Varna','+359');
INSERT INTO V_AGENCIES_NONUMBER
VALUES('T4 Tour', 'Bulgaria', 'Varna',null);
INSERT INTO V_ALLINF_AGENCIES
VALUES('T4 Tour', 'Bulgaria', 'Sofia','+359');

DROP VIEW V_FLIGHTS_INF;
DROP VIEW V_MAXCOUNTCLIENT_BOOKINGS;
DROP VIEW V_ALLINF_AGENCIES;
DROP VIEW V_AGENCIES_NONUMBER;