USE movies;

/*
SELECT TITLE, YEAR, LENGTH
FROM MOVIE
WHERE LENGTH > 120 AND YEAR < 2000 OR LENGTH IS NULL;
*/

/*
SELECT NAME, GENDER
FROM MOVIESTAR
WHERE BIRTHDATE > 1948 AND NAME LIKE 'J%'
ORDER BY NAME DESC;
*/

/*
SELECT STUDIONAME, COUNT(DISTINCT STARNAME) AS STARSNUM
FROM MOVIE JOIN STARSIN ON TITLE = MOVIETITLE
GROUP BY STUDIONAME;
*/

/*
SELECT STARNAME, COUNT(MOVIETITLE) AS MOVIESNUM
FROM STARSIN
GROUP BY STARNAME;
*/

/*
SELECT STUDIONAME, TITLE, YEAR
FROM MOVIE AS M
WHERE TITLE IN (SELECT TOP 1 TITLE FROM MOVIE AS M1 WHERE M.STUDIONAME = M1.STUDIONAME ORDER BY YEAR DESC);
*/

/*
SELECT TOP 1 NAME, BIRTHDATE
FROM MOVIESTAR
WHERE GENDER = 'M'
ORDER BY BIRTHDATE DESC;
*/

/*
SELECT STUDIONAME, STARNAME, COUNT(MOVIETITLE) AS FIMLCOUNT
FROM STARSIN JOIN MOVIE AS M ON MOVIETITLE = TITLE
GROUP BY STUDIONAME, STARNAME
HAVING COUNT(MOVIETITLE) >= ALL(SELECT COUNT(MOVIETITLE)
FROM STARSIN JOIN MOVIE ON MOVIETITLE = MOVIE.TITLE
WHERE STUDIONAME = M.STUDIONAME
GROUP BY STUDIONAME, STARNAME)
*/

/*
SELECT MOVIETITLE, MOVIEYEAR, COUNT(STARNAME) AS STARSNUM
FROM STARSIN
GROUP BY MOVIETITLE, MOVIEYEAR
HAVING COUNT(STARNAME) >= 3;
*/

